name: Deploy to Heroku

on:
  push:
    branches:
    - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'fwms-heroku' }}

jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
	
  # Trigger FWMS Tests
  ping:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: PING - Dispatch initiating repository event
      run: |
        curl -X POST https://api.github.com/jcncs/FWMS_Tests/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.FWMS_ACCESS_TOKEN }} \
        --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
